handle unknown index types gracefully in iUtils
druid-io/druid-console pull request #18
Opened 2018-02-23 00:49 UTC by alperkokmen

this updates `parseTaskId` in `iUtils.coffee` which uses a somwhat strict regular expression to parse a given task id and extract `type`, `datasource`, and time (relates to #3 and #9).

this simply removes throwing the error and falls back to `'Unknown'` for type leaving `dataSource` and `dataTime` alone. in case of a match failure, they would just default to undefined which isn't a blocker to render `/indexing-service` view.

2018-03-21 19:03 UTC, alperkokmen commented
hey @xvrl, could you please take a look when you get a chance?

2018-03-26 19:58 UTC, xvrl commented
Hi @alperkokmen, I'm not sure I'm the best person to review this. @drcrallen looks like you've made changes to this logic before, mind taking a look?

2018-04-23 21:36 UTC, alperkokmen commented
just came across a new issue (https://github.com/druid-io/druid-console/issues/19) that these changes would take care of. @drcrallen, could you please take a look?

2018-10-10 22:39 UTC, alperkokmen commented
bump – @drcrallen, could you please take a look or tag someone who can review/merge this change? thanks!

2018-10-11 01:27 UTC, clintropolis requested changes
Could you add a unit test for this behavior?

2018-10-11 19:09 UTC, alperkokmen commented
@clintropolis i found out `parseTaskId` was broken in an earlier commit while adding unit tests. 117cc36 addresses that regression with unit tests to make sure it works the way it was intended to for known tasks. ea4f4db adds the support for not throwing an error for not-so-commonly-used tasks.

2018-10-11 19:13 UTC, clintropolis approved these changes
Awesome thanks! LGTM :+1:

2018-10-11 19:16 UTC, dclim commented
👍

2018-10-11 19:17 UTC, merged